const STEP_DEFS = [
  {
    title: "Step 1 - Pre-filled prenatal profile loaded",
    text:
      "Care opens with main prenatal pipeline fields pre-filled from EHR. The only required patient input is Last Menstrual Period (LMP).",
    bullets: [
      "MedGemma receives first name, last name, DOB, gender, prior conditions, symptoms, medications, and allergies.",
      "Gemini form UI is ready but still waiting for LMP to unlock next actions.",
      "No oversight escalation is needed yet.",
    ],
    tab: "careTab",
    highlights: ["patientProfileCard", "lmpFieldWrap"],
  },
  {
    title: "Step 2 - LMP captured",
    text:
      "The patient confirms LMP. MedGemma can now compute gestational timeline boundaries and prepare visit scheduling logic.",
    bullets: [
      "LMP is the only missing structured field.",
      "MedGemma marks intake completeness as ready.",
      "Oversight receives only high-level intake status.",
    ],
    tab: "careTab",
    highlights: ["lmpFieldWrap", "commentaryBox"],
  },
  {
    title: "Step 3 - Modality preference requested",
    text:
      "In Care chat, MedGemma asks for visit modality preference. The response form is embedded directly in the conversation and generated by Gemini UI.",
    bullets: [
      "Question appears in chat as an LLM prompt.",
      "Gemini-generated form presents telemedicine vs in-person patterns.",
      "Structured response enables deterministic plan generation.",
    ],
    tab: "careTab",
    highlights: ["modalityCard", "careChatBox"],
  },
  {
    title: "Step 4 - Modality form submitted",
    text:
      "The patient submits modality preference through the structured form. MedGemma logs the preference for schedule personalization.",
    bullets: [
      "Form response is normalized to planning constraints.",
      "Care status advances to plan-generation ready.",
      "Oversight still sees status only, no full transcript.",
    ],
    tab: "careTab",
    highlights: ["careChatBox", "llmModalityForm"],
  },
  {
    title: "Step 5 - Week 1 to Week 28 plan generated",
    text:
      "MedGemma generates a prenatal report from Week 1 through Week 28 with 10 visits, key tests, and a timeline image.",
    bullets: [
      "Report includes visit cadence and test milestones.",
      "Timeline image is generated and attached to the plan.",
      "Plan is now ready for oversight and clinician handoff.",
    ],
    tab: "careTab",
    highlights: ["planReportCard", "careTimelineImage"],
  },
  {
    title: "Step 6 - Oversight Cockpit high-level monitoring",
    text:
      "Oversight displays only high-level statuses and intervention controls. Full conversation is intentionally hidden in this view.",
    bullets: [
      "Nurse sees intake completion, modality capture, and plan-generation states.",
      "Takeover can be toggled if policy or safety requires intervention.",
      "No raw full transcript is shown in oversight.",
    ],
    tab: "oversightTab",
    highlights: ["oversightStatusCard", "takeoverBtn"],
  },
  {
    title: "Step 7 - Clinician receives plan in Cockpit v2",
    text:
      "The same MedGemma plan appears in Clinician Cockpit v2 with an agent window for direct instruction-driven modifications.",
    bullets: [
      "Clinician has report + timeline context.",
      "MedGemma agent accepts natural-language edit instructions.",
      "All edits are tracked in a change log.",
    ],
    tab: "clinicianTab",
    highlights: ["clinicianPlanCard", "agentCard"],
  },
  {
    title: "Step 8 - MedASR transcription + agent refinement",
    text:
      "MedASR transcribes patient-clinician conversation. MedGemma consumes transcript snippets and proposes plan refinements.",
    bullets: [
      "Transcription is appended as structured segments.",
      "Clinician can apply MedGemma modifications from transcript context.",
      "End-to-end demo completes with care + oversight + clinician loop.",
    ],
    tab: "clinicianTab",
    highlights: ["medasrCard", "transcriptionLog", "applyAgentBtn"],
  },
];

const BASE_VISITS = [
  { visit: "V1", week: "Week 1", modality: "In-person", tests: "Intake + LMP confirmation + baseline counseling" },
  { visit: "V2", week: "Week 4", modality: "In-person", tests: "CBC, blood type, infectious screening panel" },
  { visit: "V3", week: "Week 8", modality: "Telemedicine", tests: "Symptom check + nutrition + nausea management" },
  { visit: "V4", week: "Week 12", modality: "In-person", tests: "NT planning + BP + urine protein" },
  { visit: "V5", week: "Week 16", modality: "Telemedicine", tests: "Medication review + warning signs screen" },
  { visit: "V6", week: "Week 20", modality: "In-person", tests: "Anatomy scan review + fetal growth check" },
  { visit: "V7", week: "Week 22", modality: "Telemedicine", tests: "Lifestyle reinforcement + symptom follow-up" },
  { visit: "V8", week: "Week 24", modality: "In-person", tests: "Glucose screen + BP + urine" },
  { visit: "V9", week: "Week 26", modality: "Telemedicine", tests: "CBC follow-up + vaccine counseling (Tdap)" },
  { visit: "V10", week: "Week 28", modality: "In-person", tests: "Growth review + delivery planning kickoff" },
];

const PREFILLED_PIPELINE_FIELDS = {
  patient_first_name: "Emma",
  patient_last_name: "Rodriguez",
  patient_dob: "1994-06-17",
  gender: "Female",
  previous_health_conditions: "Mild chronic hypertension",
  current_health_problems: "Intermittent headaches",
  current_medications: "Prenatal vitamin, low-dose aspirin",
  standard_allergies: "Penicillin",
};

const MODALITY_OPTIONS = [
  "In-person first, then telemedicine mix",
  "Telemedicine first, in-person only when needed",
];

const TRANSCRIPT_SEGMENTS = [
  { speaker: "Patient", text: "I can come in person this month, but telemedicine is easier after that." },
  { speaker: "Clinician", text: "That works. We will keep testing visits in-person and use virtual check-ins between them." },
  { speaker: "Patient", text: "Can we move my glucose screening to a morning slot?" },
  { speaker: "Clinician", text: "Yes, I will update week 24 testing to your preferred morning window." },
];

const state = {
  currentStep: 0,
  activeTab: "careTab",
  lmpDate: "",
  modalityChoice: "",
  takeoverActive: false,
  clinicianChanges: [],
  transcriptCount: 0,
};

const tabButtons = Array.from(document.querySelectorAll(".tab-btn"));
const tabPanels = Array.from(document.querySelectorAll(".tab-panel"));

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function setActiveTab(tabId) {
  state.activeTab = tabId;
  tabButtons.forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.tabTarget === tabId);
  });
  tabPanels.forEach((panel) => {
    panel.classList.toggle("active", panel.id === tabId);
  });
}

function getDerivedState(step) {
  const lmpDate = state.lmpDate || (step >= 1 ? "2025-08-14" : "");
  const modalityChoice =
    state.modalityChoice || (step >= 3 ? "In-person first, then telemedicine mix" : "");

  const statusItems = [
    {
      label:
        "Main pre-fill fields complete (first/last name, DOB, gender, history, meds, allergies)",
      complete: true,
    },
    { label: "LMP captured", complete: step >= 1 },
    { label: "Modality question sent by MedGemma", complete: step >= 2 },
    { label: "Gemini form response captured", complete: step >= 3 },
    { label: "Week 1-28 plan generated (10 visits)", complete: step >= 4 },
    { label: "Handoff to clinician cockpit", complete: step >= 6 },
  ];

  const oversightNotes = [
    "High-level only: patient record pre-fill confirmed.",
    step >= 1 ? "High-level only: intake complete (LMP captured)." : "Pending: intake completion.",
    step >= 3 ? "High-level only: modality preference captured via Gemini form UI." : "Pending: modality capture.",
    step >= 4 ? "High-level only: MedGemma prenatal plan generated." : "Pending: plan generation.",
    state.takeoverActive ? "Nurse takeover currently active." : "Nurse takeover currently inactive.",
  ];

  const careMessages = [];
  if (step >= 2) {
    careMessages.push({
      role: "assistant",
      author: "Care Assistant (MedGemma)",
      text:
        "Thanks, I now have your LMP. To personalize your Week 1 to Week 28 prenatal plan, please choose preferred visit modality.",
    });
    careMessages.push({
      role: "assistant",
      author: "UI Generator (Gemini)",
      text:
        "I rendered an LLM-generated structured modality form directly inside this chat so your response is captured as normalized planning data.",
      hasEmbeddedForm: true,
    });
  }
  if (step >= 3) {
    careMessages.push({
      role: "patient",
      author: "Emma Rodriguez",
      text: `Submitted modality preference form response: ${modalityChoice}.`,
    });
  }
  if (step >= 4) {
    careMessages.push({
      role: "assistant",
      author: "Care Planner (MedGemma)",
      text:
        "Prenatal plan generated successfully: Week 1 through Week 28, 10 visits, timeline image attached, and test milestones included.",
    });
  }

  const clinicianSummary = step >= 6
    ? `Clinician view of MedGemma report:
- LMP: ${lmpDate}
- Modality preference: ${modalityChoice || "Pending"}
- Coverage: Week 1 through Week 28
- Visits: 10 scheduled touchpoints with mixed modality
- Priority tests: baseline labs, anatomy scan, glucose screening, CBC follow-up`
    : "Clinician handoff pending.";

  return {
    lmpDate,
    modalityChoice,
    statusItems,
    oversightNotes,
    careMessages,
    clinicianSummary,
    planReady: step >= 4,
    modalityFormEnabled: step >= 2,
    modalitySubmitted: step >= 3,
    oversightReady: step >= 5,
    clinicianReady: step >= 6,
    transcriptionReady: step >= 7,
    commentaryContext: {
      lmpDate: lmpDate || "Not captured",
      modality: modalityChoice || "Not captured",
      careFormSource: "Main fields align with PrenatalCare/FormEHR labels",
    },
  };
}

function renderCommentary(step, derived) {
  const def = STEP_DEFS[step];
  document.getElementById("stepLabel").textContent = `Step ${step + 1} of ${STEP_DEFS.length}`;
  document.getElementById("commentaryTitle").textContent = def.title;
  const commentaryText = `${def.text} Current capture -> LMP: ${derived.commentaryContext.lmpDate}; Modality: ${derived.commentaryContext.modality}.`;
  document.getElementById("commentaryText").textContent = commentaryText;
  document.getElementById("commentaryBullets").innerHTML = [...def.bullets, derived.commentaryContext.careFormSource]
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  document.getElementById("prevStepBtn").disabled = step === 0;
  document.getElementById("nextStepBtn").disabled = step === STEP_DEFS.length - 1;
}

function renderHighlights(step) {
  document.querySelectorAll(".highlight").forEach((el) => el.classList.remove("highlight"));
  STEP_DEFS[step].highlights.forEach((id) => {
    const element = document.getElementById(id);
    if (element) {
      element.classList.add("highlight");
    }
  });
}

function renderEmbeddedModalityForm(derived) {
  const formLocked = Boolean(derived.modalitySubmitted);
  const optionsMarkup = MODALITY_OPTIONS.map((option) => `
      <label class="radio-card embedded-option">
        <input
          type="radio"
          name="embeddedModalityChoice"
          value="${escapeHtml(option)}"
          ${derived.modalityChoice === option ? "checked" : ""}
          ${!derived.modalityFormEnabled || formLocked ? "disabled" : ""}
        />
        <span>${escapeHtml(option)}</span>
      </label>
  `).join("");

  return `
    <div class="llm-form-shell" id="llmModalityForm">
      <div class="llm-form-title">LLM-generated form (Gemini UI)</div>
      <div class="llm-form-help">
        This form was generated inside the conversation from a MedGemma prompt.
      </div>
      ${formLocked ? '<div class="llm-form-help">Response submitted and locked.</div>' : ""}
      <form id="embeddedModalityForm" class="embedded-form-grid">
        <div class="embedded-label">Visit modality preference</div>
        ${optionsMarkup}
        <div class="form-actions">
          <button
            id="embeddedSubmitModalityBtn"
            class="btn btn-secondary"
            type="submit"
            ${!derived.modalityFormEnabled || formLocked ? "disabled" : ""}
          >
            Submit modality form response
          </button>
        </div>
      </form>
    </div>
  `;
}

function renderCare(derived) {
  document.getElementById("patientFirstNameField").value = PREFILLED_PIPELINE_FIELDS.patient_first_name;
  document.getElementById("patientLastNameField").value = PREFILLED_PIPELINE_FIELDS.patient_last_name;
  document.getElementById("patientDobField").value = PREFILLED_PIPELINE_FIELDS.patient_dob;
  document.getElementById("patientGenderField").value = PREFILLED_PIPELINE_FIELDS.gender;
  document.getElementById("prevHealthField").value = PREFILLED_PIPELINE_FIELDS.previous_health_conditions;
  document.getElementById("currentSymptomsField").value = PREFILLED_PIPELINE_FIELDS.current_health_problems;
  document.getElementById("currentMedsField").value = PREFILLED_PIPELINE_FIELDS.current_medications;
  document.getElementById("standardAllergiesField").value = PREFILLED_PIPELINE_FIELDS.standard_allergies;

  document.getElementById("lmpDateInput").value = derived.lmpDate;
  const confirmLmpBtn = document.getElementById("confirmLmpBtn");
  confirmLmpBtn.disabled = false;

  const careChatBox = document.getElementById("careChatBox");
  if (derived.careMessages.length === 0) {
    careChatBox.innerHTML = '<div class="message assistant"><span class="meta">Care Assistant (MedGemma)</span>Waiting for LMP to start modality planning.</div>';
  } else {
    careChatBox.innerHTML = derived.careMessages
      .map(
        (msg) => `
          <div class="message ${escapeHtml(msg.role)}">
            <span class="meta">${escapeHtml(msg.author)}</span>
            ${escapeHtml(msg.text)}
            ${msg.hasEmbeddedForm ? renderEmbeddedModalityForm(derived) : ""}
          </div>`
      )
      .join("");
  }

  const summary = document.getElementById("planSummary");
  const planCard = document.getElementById("planReportCard");
  const visitTableBody = document.getElementById("visitTableBody");
  const timeline = document.getElementById("careTimelineImage");

  if (!derived.planReady) {
    summary.textContent = "Plan not generated yet. MedGemma will create the Week 1 to Week 28 report after modality response.";
    visitTableBody.innerHTML = "";
    timeline.style.opacity = "0.2";
    planCard.style.opacity = "0.7";
    return;
  }

  planCard.style.opacity = "1";
  timeline.style.opacity = "1";
  summary.textContent = `Generated by MedGemma using LMP ${derived.lmpDate} and modality preference "${derived.modalityChoice}". Includes 10 visits with tests and a timeline image.`;
  visitTableBody.innerHTML = BASE_VISITS.map((row) => `
    <tr>
      <td>${escapeHtml(row.visit)}</td>
      <td>${escapeHtml(row.week)}</td>
      <td>${escapeHtml(row.modality)}</td>
      <td>${escapeHtml(row.tests)}</td>
    </tr>
  `).join("");
}

function renderOversight(derived) {
  const statuses = document.getElementById("oversightStatuses");
  statuses.innerHTML = derived.statusItems
    .map(
      (item) => `
      <div class="status-item ${item.complete ? "complete" : "pending"}">
        ${item.complete ? "Complete" : "Pending"}: ${escapeHtml(item.label)}
      </div>`
    )
    .join("");

  const notes = document.getElementById("oversightNotes");
  notes.innerHTML = derived.oversightNotes
    .map((note) => `<div class="event-item">${escapeHtml(note)}</div>`)
    .join("");

  const takeoverBtn = document.getElementById("takeoverBtn");
  takeoverBtn.disabled = !derived.oversightReady;
  document.getElementById("takeoverState").textContent = state.takeoverActive
    ? "Takeover active"
    : "Takeover inactive";
}

function renderClinician(derived) {
  const summary = document.getElementById("clinicianPlanSummary");
  summary.textContent = derived.clinicianSummary;

  const clinicianTimeline = document.getElementById("clinicianTimelineImage");
  clinicianTimeline.style.opacity = derived.clinicianReady ? "1" : "0.2";

  const applyAgentBtn = document.getElementById("applyAgentBtn");
  const simulateTranscriptionBtn = document.getElementById("simulateTranscriptionBtn");
  applyAgentBtn.disabled = !derived.clinicianReady;
  simulateTranscriptionBtn.disabled = !derived.transcriptionReady;

  const changesLog = document.getElementById("agentChangesLog");
  if (!derived.clinicianReady) {
    changesLog.innerHTML = '<div class="event-item">Clinician handoff pending.</div>';
  } else if (state.clinicianChanges.length === 0) {
    changesLog.innerHTML = '<div class="event-item">No clinician modifications applied yet.</div>';
  } else {
    changesLog.innerHTML = state.clinicianChanges
      .map((change) => `<div class="event-item">${escapeHtml(change)}</div>`)
      .join("");
  }

  const transcriptionLog = document.getElementById("transcriptionLog");
  if (!derived.transcriptionReady) {
    transcriptionLog.innerHTML = '<div class="message assistant"><span class="meta">MedASR</span>Transcription feed will start at Step 8.</div>';
    return;
  }

  const activeSegments = TRANSCRIPT_SEGMENTS.slice(0, Math.max(1, state.transcriptCount));
  transcriptionLog.innerHTML = activeSegments
    .map(
      (segment, idx) => `
        <div class="message clinician">
          <span class="meta">MedASR Segment ${idx + 1} | ${escapeHtml(segment.speaker)}</span>
          ${escapeHtml(segment.text)}
        </div>`
    )
    .join("");
}

function renderAll() {
  const step = state.currentStep;
  const derived = getDerivedState(step);
  const defaultTab = STEP_DEFS[step].tab;
  setActiveTab(defaultTab);
  renderCommentary(step, derived);
  renderCare(derived);
  renderOversight(derived);
  renderClinician(derived);
  renderHighlights(step);
}

function goToStep(nextStep) {
  if (nextStep < 0 || nextStep >= STEP_DEFS.length) return;
  if (nextStep < state.currentStep) {
    if (nextStep < 1) state.lmpDate = "";
    if (nextStep < 3) state.modalityChoice = "";
    if (nextStep < 7) state.transcriptCount = 0;
    if (nextStep < 6) {
      state.clinicianChanges = [];
    }
    state.takeoverActive = false;
  }
  state.currentStep = nextStep;
  renderAll();
}

function bindTabs() {
  tabButtons.forEach((btn) => {
    btn.addEventListener("click", () => {
      setActiveTab(btn.dataset.tabTarget);
    });
  });
}

function bindStepControls() {
  document.getElementById("prevStepBtn").addEventListener("click", () => {
    goToStep(state.currentStep - 1);
  });

  document.getElementById("nextStepBtn").addEventListener("click", () => {
    goToStep(state.currentStep + 1);
  });
}

function bindCareActions() {
  document.getElementById("confirmLmpBtn").addEventListener("click", () => {
    const input = document.getElementById("lmpDateInput");
    if (!input.value) return;
    state.lmpDate = input.value;
    if (state.currentStep < 1) {
      goToStep(1);
      return;
    }
    renderAll();
  });

  const careChatBox = document.getElementById("careChatBox");

  careChatBox.addEventListener("change", (event) => {
    const target = event.target;
    if (!(target instanceof HTMLInputElement)) return;
    if (target.name !== "embeddedModalityChoice") return;
    state.modalityChoice = target.value;
  });

  careChatBox.addEventListener("submit", (event) => {
    const form = event.target;
    if (!(form instanceof HTMLFormElement)) return;
    if (form.id !== "embeddedModalityForm") return;
    event.preventDefault();
    const selected = form.querySelector('input[name="embeddedModalityChoice"]:checked');
    if (!(selected instanceof HTMLInputElement)) return;
    state.modalityChoice = selected.value;
    if (state.currentStep < 3) {
      goToStep(3);
      return;
    }
    renderAll();
  });
}

function bindOversightActions() {
  document.getElementById("takeoverBtn").addEventListener("click", () => {
    if (state.currentStep < 5) return;
    state.takeoverActive = !state.takeoverActive;
    renderAll();
  });
}

function bindClinicianActions() {
  document.getElementById("applyAgentBtn").addEventListener("click", () => {
    if (state.currentStep < 6) return;
    const text = document.getElementById("agentInstructionInput").value.trim();
    if (!text) return;
    const entry = `MedGemma agent applied clinician instruction: ${text}`;
    state.clinicianChanges.push(entry);
    document.getElementById("agentInstructionInput").value = "";
    renderAll();
  });

  document.getElementById("simulateTranscriptionBtn").addEventListener("click", () => {
    if (state.currentStep < 7) return;
    state.transcriptCount = Math.min(TRANSCRIPT_SEGMENTS.length, state.transcriptCount + 1);
    if (state.transcriptCount === 0) state.transcriptCount = 1;
    renderAll();
  });
}

bindTabs();
bindStepControls();
bindCareActions();
bindOversightActions();
bindClinicianActions();
renderAll();
